#!/usr/bin/env groovy
pipeline {
    agent any

    stages {
        stage('Build Image') {
            when {
                 branch 'master'  //only run these steps on the master branch
            }
             step   {  
                 script {
                    docker.build('Dockerfile')
            }
             }

        }

        stage('Publish Image') {
            when {
              branch 'master'  //only run these steps on the master branch
            }
            step {
                script {
               docker.withRegistry('https://registry.hub.docker.com', 'dockerhub-credentials') {
                        docker.image('housing-price-prediction').push('latest') }
            }
            }
        }
    }
}
